### ISSUE TITLE
Publication

### ISSUE THREAD

**Issue by fearocanity** [willyb321/every-knights-and-magic-frame#1]
Set your Facebook Developer App mode to Live. I can't seem to see your post😅
I also forgot to include it in Readme, Thank you!
![Screenshot](https://github.com/willyb321/every-knights-and-magic-frame/assets/91414643/fdcc922c-cf8f-4009-a542-f0c2f354abb9)

**Comment by willyb321** [comment]
ha, i've done that just now, will see how it goes! Thanks for the notice
